# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.srcs/sources_1/ip/ddr4_1/ddr4_1.xci
# IP: The module: 'ddr4_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/ip_0/ddr4_1_microblaze_mcs.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr4_1_microblaze_mcs || ORIG_REF_NAME==ddr4_1_microblaze_mcs} -quiet] -quiet

# Block Designs: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/bd_9c58.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9c58 || ORIG_REF_NAME==bd_9c58} -quiet] -quiet

# IP: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_0/bd_9c58_microblaze_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9c58_microblaze_I_0 || ORIG_REF_NAME==bd_9c58_microblaze_I_0} -quiet] -quiet

# IP: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_1/bd_9c58_rst_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9c58_rst_0_0 || ORIG_REF_NAME==bd_9c58_rst_0_0} -quiet] -quiet

# IP: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_2/bd_9c58_ilmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9c58_ilmb_0 || ORIG_REF_NAME==bd_9c58_ilmb_0} -quiet] -quiet

# IP: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_3/bd_9c58_dlmb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9c58_dlmb_0 || ORIG_REF_NAME==bd_9c58_dlmb_0} -quiet] -quiet

# IP: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_4/bd_9c58_dlmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9c58_dlmb_cntlr_0 || ORIG_REF_NAME==bd_9c58_dlmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_5/bd_9c58_ilmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9c58_ilmb_cntlr_0 || ORIG_REF_NAME==bd_9c58_ilmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_6/bd_9c58_lmb_bram_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9c58_lmb_bram_I_0 || ORIG_REF_NAME==bd_9c58_lmb_bram_I_0} -quiet] -quiet

# IP: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_7/bd_9c58_second_dlmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9c58_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_9c58_second_dlmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_8/bd_9c58_second_ilmb_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9c58_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_9c58_second_ilmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_9/bd_9c58_second_lmb_bram_I_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9c58_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_9c58_second_lmb_bram_I_0} -quiet] -quiet

# IP: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_10/bd_9c58_iomodule_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9c58_iomodule_0_0 || ORIG_REF_NAME==bd_9c58_iomodule_0_0} -quiet] -quiet

# IP: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/ip_1/ddr4_1_phy.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr4_1_phy || ORIG_REF_NAME==ddr4_1_phy} -quiet] -quiet

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_0/bd_9c58_microblaze_I_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9c58_microblaze_I_0 || ORIG_REF_NAME==bd_9c58_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_0/bd_9c58_microblaze_I_0_ooc_debug.xdc

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_1/bd_9c58_rst_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9c58_rst_0_0 || ORIG_REF_NAME==bd_9c58_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_1/bd_9c58_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9c58_rst_0_0 || ORIG_REF_NAME==bd_9c58_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_2/bd_9c58_ilmb_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9c58_ilmb_0 || ORIG_REF_NAME==bd_9c58_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_3/bd_9c58_dlmb_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9c58_dlmb_0 || ORIG_REF_NAME==bd_9c58_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_6/bd_9c58_lmb_bram_I_0_ooc.xdc

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_9/bd_9c58_second_lmb_bram_I_0_ooc.xdc

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_10/bd_9c58_iomodule_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9c58_iomodule_0_0 || ORIG_REF_NAME==bd_9c58_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/bd_9c58_ooc.xdc

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/ip_0/ddr4_1_microblaze_mcs_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr4_1_microblaze_mcs || ORIG_REF_NAME==ddr4_1_microblaze_mcs} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/ip_0/ddr4_1_microblaze_mcs_ooc.xdc

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/ip_1/par/ddr4_1_phy_ooc.xdc

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/ddr4_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr4_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/par/ddr4_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr4_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.srcs/sources_1/ip/ddr4_1/ddr4_1.xci
# IP: The module: 'ddr4_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/ip_0/ddr4_1_microblaze_mcs.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr4_1_microblaze_mcs || ORIG_REF_NAME==ddr4_1_microblaze_mcs} -quiet] -quiet

# Block Designs: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/bd_9c58.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9c58 || ORIG_REF_NAME==bd_9c58} -quiet] -quiet

# IP: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_0/bd_9c58_microblaze_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9c58_microblaze_I_0 || ORIG_REF_NAME==bd_9c58_microblaze_I_0} -quiet] -quiet

# IP: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_1/bd_9c58_rst_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9c58_rst_0_0 || ORIG_REF_NAME==bd_9c58_rst_0_0} -quiet] -quiet

# IP: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_2/bd_9c58_ilmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9c58_ilmb_0 || ORIG_REF_NAME==bd_9c58_ilmb_0} -quiet] -quiet

# IP: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_3/bd_9c58_dlmb_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9c58_dlmb_0 || ORIG_REF_NAME==bd_9c58_dlmb_0} -quiet] -quiet

# IP: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_4/bd_9c58_dlmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9c58_dlmb_cntlr_0 || ORIG_REF_NAME==bd_9c58_dlmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_5/bd_9c58_ilmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9c58_ilmb_cntlr_0 || ORIG_REF_NAME==bd_9c58_ilmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_6/bd_9c58_lmb_bram_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9c58_lmb_bram_I_0 || ORIG_REF_NAME==bd_9c58_lmb_bram_I_0} -quiet] -quiet

# IP: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_7/bd_9c58_second_dlmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9c58_second_dlmb_cntlr_0 || ORIG_REF_NAME==bd_9c58_second_dlmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_8/bd_9c58_second_ilmb_cntlr_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9c58_second_ilmb_cntlr_0 || ORIG_REF_NAME==bd_9c58_second_ilmb_cntlr_0} -quiet] -quiet

# IP: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_9/bd_9c58_second_lmb_bram_I_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9c58_second_lmb_bram_I_0 || ORIG_REF_NAME==bd_9c58_second_lmb_bram_I_0} -quiet] -quiet

# IP: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_10/bd_9c58_iomodule_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_9c58_iomodule_0_0 || ORIG_REF_NAME==bd_9c58_iomodule_0_0} -quiet] -quiet

# IP: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/ip_1/ddr4_1_phy.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ddr4_1_phy || ORIG_REF_NAME==ddr4_1_phy} -quiet] -quiet

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_0/bd_9c58_microblaze_I_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9c58_microblaze_I_0 || ORIG_REF_NAME==bd_9c58_microblaze_I_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_0/bd_9c58_microblaze_I_0_ooc_debug.xdc

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_1/bd_9c58_rst_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9c58_rst_0_0 || ORIG_REF_NAME==bd_9c58_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_1/bd_9c58_rst_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9c58_rst_0_0 || ORIG_REF_NAME==bd_9c58_rst_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_2/bd_9c58_ilmb_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9c58_ilmb_0 || ORIG_REF_NAME==bd_9c58_ilmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_3/bd_9c58_dlmb_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9c58_dlmb_0 || ORIG_REF_NAME==bd_9c58_dlmb_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_6/bd_9c58_lmb_bram_I_0_ooc.xdc

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_9/bd_9c58_second_lmb_bram_I_0_ooc.xdc

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/ip/ip_10/bd_9c58_iomodule_0_0_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_9c58_iomodule_0_0 || ORIG_REF_NAME==bd_9c58_iomodule_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/bd_0/bd_9c58_ooc.xdc

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/ip_0/ddr4_1_microblaze_mcs_board.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ddr4_1_microblaze_mcs || ORIG_REF_NAME==ddr4_1_microblaze_mcs} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/ip_0/ddr4_1_microblaze_mcs_ooc.xdc

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/ip_1/par/ddr4_1_phy_ooc.xdc

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/ddr4_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr4_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/par/ddr4_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'ddr4_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
