# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xusps3_config/xusps3_pinout.xdc

# IP: ip/xdma_0/xdma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_0 || ORIG_REF_NAME==xdma_0} -quiet] -quiet
