# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/.Xil/Vivado-18760-DESKTOP-ILOVGO9/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xcvu095-ffva2104-1-i
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/ip_1/rtl/map
    c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/rtl/ip_top
    c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/rtl/cal
  } {
      C:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/imports/ddrx_cal_mc_odt.sv
      C:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/imports/example_tb_phy.sv
      C:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/imports/example_top.sv
    }
      rt::read_verilog -sv -include {
    c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/ip_1/rtl/map
    c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/rtl/ip_top
    c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/rtl/cal
  } D:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      rt::read_verilog -include {
    c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/ip_1/rtl/map
    c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/rtl/ip_top
    c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/ddr4_1_ex.gen/sources_1/ip/ddr4_1/rtl/cal
  } C:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/.Xil/Vivado-18760-DESKTOP-ILOVGO9/realtime/ddr4_1_stub.v
      rt::read_vhdl -lib xpm D:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top example_top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/ddr4_1_ex/.Xil/Vivado-18760-DESKTOP-ILOVGO9/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
