set_property SRC_FILE_INFO {cfile:c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/project_1/project_1.srcs/sources_1/ip/xdma_0/ip_0/ip_0/synth/xdma_0_pcie3_ip_gt.xdc rfile:../../../project_1.srcs/sources_1/ip/xdma_0/ip_0/ip_0/synth/xdma_0_pcie3_ip_gt.xdc id:1 order:EARLY scoped_inst:EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/project_1/project_1.srcs/sources_1/ip/xdma_0/ip_0/source/xdma_0_pcie3_ip-PCIE_X0Y0.xdc rfile:../../../project_1.srcs/sources_1/ip/xdma_0/ip_0/source/xdma_0_pcie3_ip-PCIE_X0Y0.xdc id:2 order:EARLY scoped_inst:EP/xdma_0_i/inst/pcie3_ip_i/inst} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/project_1/project_1.srcs/constrs_1/imports/xusps3_config/xusps3_pinout.xdc rfile:../../../project_1.srcs/constrs_1/imports/xusps3_config/xusps3_pinout.xdc id:3} [current_design]
current_instance EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE3_CHANNEL_X0Y0 [get_cells -hierarchical -filter {NAME =~ *gen_channel_container[0].*gen_gthe3_channel_inst[0].GTHE3_CHANNEL_PRIM_INST}]
set_property src_info {type:SCOPED_XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE3_CHANNEL_X0Y1 [get_cells -hierarchical -filter {NAME =~ *gen_channel_container[0].*gen_gthe3_channel_inst[1].GTHE3_CHANNEL_PRIM_INST}]
set_property src_info {type:SCOPED_XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE3_CHANNEL_X0Y2 [get_cells -hierarchical -filter {NAME =~ *gen_channel_container[0].*gen_gthe3_channel_inst[2].GTHE3_CHANNEL_PRIM_INST}]
set_property src_info {type:SCOPED_XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE3_CHANNEL_X0Y3 [get_cells -hierarchical -filter {NAME =~ *gen_channel_container[0].*gen_gthe3_channel_inst[3].GTHE3_CHANNEL_PRIM_INST}]
set_property src_info {type:SCOPED_XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE3_CHANNEL_X0Y4 [get_cells -hierarchical -filter {NAME =~ *gen_channel_container[1].*gen_gthe3_channel_inst[0].GTHE3_CHANNEL_PRIM_INST}]
set_property src_info {type:SCOPED_XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE3_CHANNEL_X0Y5 [get_cells -hierarchical -filter {NAME =~ *gen_channel_container[1].*gen_gthe3_channel_inst[1].GTHE3_CHANNEL_PRIM_INST}]
set_property src_info {type:SCOPED_XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE3_CHANNEL_X0Y6 [get_cells -hierarchical -filter {NAME =~ *gen_channel_container[1].*gen_gthe3_channel_inst[2].GTHE3_CHANNEL_PRIM_INST}]
set_property src_info {type:SCOPED_XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC GTHE3_CHANNEL_X0Y7 [get_cells -hierarchical -filter {NAME =~ *gen_channel_container[1].*gen_gthe3_channel_inst[3].GTHE3_CHANNEL_PRIM_INST}]
current_instance
current_instance EP/xdma_0_i/inst/pcie3_ip_i/inst
set_property src_info {type:SCOPED_XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC PCIE_3_1_X0Y0 [get_cells xdma_0_pcie3_ip_pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/PCIE_3_1_inst]
set_property src_info {type:SCOPED_XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X16Y2 [get_cells {xdma_0_pcie3_ip_pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/bram_inst/bram_req_inst/bram_req_8k_inst/RAMB18E2[0].ramb18e2_inst}]
set_property src_info {type:SCOPED_XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X16Y3 [get_cells {xdma_0_pcie3_ip_pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/bram_inst/bram_req_inst/bram_req_8k_inst/RAMB18E2[1].ramb18e2_inst}]
set_property src_info {type:SCOPED_XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X16Y4 [get_cells {xdma_0_pcie3_ip_pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/bram_inst/bram_req_inst/bram_req_8k_inst/RAMB18E2[2].ramb18e2_inst}]
set_property src_info {type:SCOPED_XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X16Y5 [get_cells {xdma_0_pcie3_ip_pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/bram_inst/bram_req_inst/bram_req_8k_inst/RAMB18E2[3].ramb18e2_inst}]
set_property src_info {type:SCOPED_XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X16Y8 [get_cells {xdma_0_pcie3_ip_pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/bram_inst/bram_cpl_inst/CPL_FIFO_16KB.bram_16k_inst/RAMB18E2[0].ramb18e2_inst}]
set_property src_info {type:SCOPED_XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X16Y9 [get_cells {xdma_0_pcie3_ip_pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/bram_inst/bram_cpl_inst/CPL_FIFO_16KB.bram_16k_inst/RAMB18E2[1].ramb18e2_inst}]
set_property src_info {type:SCOPED_XDC file:2 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X16Y10 [get_cells {xdma_0_pcie3_ip_pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/bram_inst/bram_cpl_inst/CPL_FIFO_16KB.bram_16k_inst/RAMB18E2[2].ramb18e2_inst}]
set_property src_info {type:SCOPED_XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB18_X16Y11 [get_cells {xdma_0_pcie3_ip_pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/bram_inst/bram_cpl_inst/CPL_FIFO_16KB.bram_16k_inst/RAMB18E2[3].ramb18e2_inst}]
set_property src_info {type:SCOPED_XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X16Y9 [get_cells {xdma_0_pcie3_ip_pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/bram_inst/bram_rep_inst/bram_rep_8k_inst/RAMB36E2[0].ramb36e2_inst}]
set_property src_info {type:SCOPED_XDC file:2 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property LOC RAMB36_X16Y10 [get_cells {xdma_0_pcie3_ip_pcie3_uscale_top_inst/pcie3_uscale_wrapper_inst/bram_inst/bram_rep_inst/bram_rep_8k_inst/RAMB36E2[1].ramb36e2_inst}]
set_property src_info {type:SCOPED_XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_nets {xdma_0_pcie3_ip_gt_top_i/PHY_TXOUTCLKSEL[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_nets {xdma_0_pcie3_ip_gt_top_i/PHY_TXOUTCLKSEL[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_nets {xdma_0_pcie3_ip_gt_top_i/PHY_TXOUTCLKSEL[0]}]
current_instance
set_property src_info {type:SCOPED_XDC file:2 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins [list {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[0].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[0].GTHE3_CHANNEL_PRIM_INST/TXRATE[0]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[0].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[1].GTHE3_CHANNEL_PRIM_INST/TXRATE[0]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[0].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[2].GTHE3_CHANNEL_PRIM_INST/TXRATE[0]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[0].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[3].GTHE3_CHANNEL_PRIM_INST/TXRATE[0]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[1].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[0].GTHE3_CHANNEL_PRIM_INST/TXRATE[0]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[1].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[1].GTHE3_CHANNEL_PRIM_INST/TXRATE[0]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[1].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[2].GTHE3_CHANNEL_PRIM_INST/TXRATE[0]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[1].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[3].GTHE3_CHANNEL_PRIM_INST/TXRATE[0]}]]
set_property src_info {type:SCOPED_XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins [list {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[0].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[0].GTHE3_CHANNEL_PRIM_INST/RXRATE[0]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[0].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[1].GTHE3_CHANNEL_PRIM_INST/RXRATE[0]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[0].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[2].GTHE3_CHANNEL_PRIM_INST/RXRATE[0]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[0].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[3].GTHE3_CHANNEL_PRIM_INST/RXRATE[0]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[1].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[0].GTHE3_CHANNEL_PRIM_INST/RXRATE[0]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[1].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[1].GTHE3_CHANNEL_PRIM_INST/RXRATE[0]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[1].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[2].GTHE3_CHANNEL_PRIM_INST/RXRATE[0]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[1].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[3].GTHE3_CHANNEL_PRIM_INST/RXRATE[0]}]]
set_property src_info {type:SCOPED_XDC file:2 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins [list {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[0].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[0].GTHE3_CHANNEL_PRIM_INST/TXRATE[1]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[0].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[1].GTHE3_CHANNEL_PRIM_INST/TXRATE[1]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[0].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[2].GTHE3_CHANNEL_PRIM_INST/TXRATE[1]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[0].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[3].GTHE3_CHANNEL_PRIM_INST/TXRATE[1]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[1].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[0].GTHE3_CHANNEL_PRIM_INST/TXRATE[1]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[1].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[1].GTHE3_CHANNEL_PRIM_INST/TXRATE[1]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[1].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[2].GTHE3_CHANNEL_PRIM_INST/TXRATE[1]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[1].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[3].GTHE3_CHANNEL_PRIM_INST/TXRATE[1]}]]
set_property src_info {type:SCOPED_XDC file:2 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins [list {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[0].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[0].GTHE3_CHANNEL_PRIM_INST/RXRATE[1]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[0].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[1].GTHE3_CHANNEL_PRIM_INST/RXRATE[1]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[0].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[2].GTHE3_CHANNEL_PRIM_INST/RXRATE[1]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[0].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[3].GTHE3_CHANNEL_PRIM_INST/RXRATE[1]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[1].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[0].GTHE3_CHANNEL_PRIM_INST/RXRATE[1]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[1].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[1].GTHE3_CHANNEL_PRIM_INST/RXRATE[1]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[1].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[2].GTHE3_CHANNEL_PRIM_INST/RXRATE[1]} {EP/xdma_0_i/inst/pcie3_ip_i/inst/xdma_0_pcie3_ip_gt_top_i/gt_wizard.gtwizard_top_i/xdma_0_pcie3_ip_gt_i/inst/gen_gtwizard_gthe3_top.xdma_0_pcie3_ip_gt_gtwizard_gthe3_inst/gen_gtwizard_gthe3.gen_channel_container[1].gen_enabled_channel.gthe3_channel_wrapper_inst/channel_inst/gthe3_channel_gen.gen_gthe3_channel_inst[3].GTHE3_CHANNEL_PRIM_INST/RXRATE[1]}]]
current_instance EP/xdma_0_i/inst/pcie3_ip_i/inst
set_property src_info {type:SCOPED_XDC file:2 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {xdma_0_pcie3_ip_gt_top_i/phy_clk_i/bufg_gt_userclk/DIV[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {xdma_0_pcie3_ip_gt_top_i/phy_clk_i/bufg_gt_userclk/DIV[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {xdma_0_pcie3_ip_gt_top_i/phy_clk_i/bufg_gt_userclk/DIV[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {xdma_0_pcie3_ip_gt_top_i/phy_clk_i/bufg_gt_pclk/DIV[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {xdma_0_pcie3_ip_gt_top_i/phy_clk_i/bufg_gt_pclk/DIV[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {xdma_0_pcie3_ip_gt_top_i/phy_clk_i/bufg_gt_pclk/DIV[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 1 [get_pins {xdma_0_pcie3_ip_gt_top_i/bufg_mcap_clk/DIV[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {xdma_0_pcie3_ip_gt_top_i/bufg_mcap_clk/DIV[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {xdma_0_pcie3_ip_gt_top_i/bufg_mcap_clk/DIV[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {xdma_0_pcie3_ip_gt_top_i/phy_clk_i/bufg_gt_coreclk/DIV[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {xdma_0_pcie3_ip_gt_top_i/phy_clk_i/bufg_gt_coreclk/DIV[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_case_analysis 0 [get_pins {xdma_0_pcie3_ip_gt_top_i/phy_clk_i/bufg_gt_coreclk/DIV[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:201 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-1} -internal -scoped -tags "1019576" -desc "properly_synced" -from [get_pins -filter {REF_PIN_NAME=~C} -of_objects [get_cells -hierarchical -filter { NAME =~ *pipe_misc_inst/pipe_stages_1.pipe_tx_rate_q_reg[*]}]] -to [get_pins -filter {REF_PIN_NAME=~D} -of_objects [get_cells -hierarchical -filter { NAME =~ *rxlpmen_i_reg[*]}]]
current_instance
set_property src_info {type:XDC file:3 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR26 [get_ports pci_rst_n]
set_property src_info {type:XDC file:3 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV18 [get_ports phy_clk_p]
set_property src_info {type:XDC file:3 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT23 [get_ports phy_rst_n]
set_property src_info {type:XDC file:3 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT10 [get_ports "pci_clk_n"]
set_property src_info {type:XDC file:3 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV22 [get_ports "c0_init_calib_complete"]
set_property src_info {type:XDC file:3 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR22 [get_ports {leds[0]}]
set_property src_info {type:XDC file:3 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT22 [get_ports {leds[1]}]
set_property src_info {type:XDC file:3 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR23 [get_ports {leds[2]}]
set_property src_info {type:XDC file:3 line:357 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT18 [ get_ports "c0_ddr4_adr[0]" ]
set_property src_info {type:XDC file:3 line:358 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU17 [ get_ports "c0_ddr4_adr[1]" ]
set_property src_info {type:XDC file:3 line:359 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP19 [ get_ports "c0_ddr4_adr[10]" ]
set_property src_info {type:XDC file:3 line:360 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM16 [ get_ports "c0_ddr4_adr[11]" ]
set_property src_info {type:XDC file:3 line:361 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN16 [ get_ports "c0_ddr4_adr[12]" ]
set_property src_info {type:XDC file:3 line:362 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL19 [ get_ports "c0_ddr4_adr[13]" ]
set_property src_info {type:XDC file:3 line:363 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM19 [ get_ports "c0_ddr4_adr[14]" ]
set_property src_info {type:XDC file:3 line:364 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL20 [ get_ports "c0_ddr4_adr[15]" ]
set_property src_info {type:XDC file:3 line:365 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM20 [ get_ports "c0_ddr4_adr[16]" ]
set_property src_info {type:XDC file:3 line:366 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP18 [ get_ports "c0_ddr4_adr[2]" ]
set_property src_info {type:XDC file:3 line:367 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR18 [ get_ports "c0_ddr4_adr[3]" ]
set_property src_info {type:XDC file:3 line:368 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP20 [ get_ports "c0_ddr4_adr[4]" ]
set_property src_info {type:XDC file:3 line:369 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR20 [ get_ports "c0_ddr4_adr[5]" ]
set_property src_info {type:XDC file:3 line:370 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU21 [ get_ports "c0_ddr4_adr[6]" ]
set_property src_info {type:XDC file:3 line:371 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN18 [ get_ports "c0_ddr4_adr[7]" ]
set_property src_info {type:XDC file:3 line:372 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN17 [ get_ports "c0_ddr4_adr[8]" ]
set_property src_info {type:XDC file:3 line:373 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN19 [ get_ports "c0_ddr4_adr[9]" ]
set_property src_info {type:XDC file:3 line:374 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV17 [ get_ports "c0_ddr4_act_n" ]
set_property src_info {type:XDC file:3 line:375 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT19 [ get_ports "c0_ddr4_ba[0]" ]
set_property src_info {type:XDC file:3 line:376 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU19 [ get_ports "c0_ddr4_ba[1]" ]
set_property src_info {type:XDC file:3 line:377 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT20 [ get_ports "c0_ddr4_bg[0]" ]
set_property src_info {type:XDC file:3 line:379 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT17 [ get_ports "c0_ddr4_ck_c[0]" ]
set_property src_info {type:XDC file:3 line:380 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR17 [ get_ports "c0_ddr4_ck_t[0]" ]
set_property src_info {type:XDC file:3 line:383 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY20 [ get_ports "c0_ddr4_cke[0]" ]
set_property src_info {type:XDC file:3 line:385 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA18 [ get_ports "c0_ddr4_cs_n[0]" ]
set_property src_info {type:XDC file:3 line:387 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR16 [ get_ports "c0_ddr4_dm_dbi_n[0]" ]
set_property src_info {type:XDC file:3 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW14 [ get_ports "c0_ddr4_dm_dbi_n[1]" ]
set_property src_info {type:XDC file:3 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA12 [ get_ports "c0_ddr4_dm_dbi_n[2]" ]
set_property src_info {type:XDC file:3 line:390 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BF14 [ get_ports "c0_ddr4_dm_dbi_n[3]" ]
set_property src_info {type:XDC file:3 line:391 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP25 [ get_ports "c0_ddr4_dm_dbi_n[4]" ]
set_property src_info {type:XDC file:3 line:392 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV26 [ get_ports "c0_ddr4_dm_dbi_n[5]" ]
set_property src_info {type:XDC file:3 line:393 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA25 [ get_ports "c0_ddr4_dm_dbi_n[6]" ]
set_property src_info {type:XDC file:3 line:394 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BF28 [ get_ports "c0_ddr4_dm_dbi_n[7]" ]
set_property src_info {type:XDC file:3 line:396 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM14 [ get_ports "c0_ddr4_dq[0]" ]
set_property src_info {type:XDC file:3 line:397 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL14 [ get_ports "c0_ddr4_dq[1]" ]
set_property src_info {type:XDC file:3 line:398 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU15 [ get_ports "c0_ddr4_dq[10]" ]
set_property src_info {type:XDC file:3 line:399 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT15 [ get_ports "c0_ddr4_dq[11]" ]
set_property src_info {type:XDC file:3 line:400 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV13 [ get_ports "c0_ddr4_dq[12]" ]
set_property src_info {type:XDC file:3 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU13 [ get_ports "c0_ddr4_dq[13]" ]
set_property src_info {type:XDC file:3 line:402 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW15 [ get_ports "c0_ddr4_dq[14]" ]
set_property src_info {type:XDC file:3 line:403 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW16 [ get_ports "c0_ddr4_dq[15]" ]
set_property src_info {type:XDC file:3 line:404 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA13 [ get_ports "c0_ddr4_dq[16]" ]
set_property src_info {type:XDC file:3 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY13 [ get_ports "c0_ddr4_dq[17]" ]
set_property src_info {type:XDC file:3 line:406 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA14 [ get_ports "c0_ddr4_dq[18]" ]
set_property src_info {type:XDC file:3 line:407 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA15 [ get_ports "c0_ddr4_dq[19]" ]
set_property src_info {type:XDC file:3 line:408 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM15 [ get_ports "c0_ddr4_dq[2]" ]
set_property src_info {type:XDC file:3 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY15 [ get_ports "c0_ddr4_dq[20]" ]
set_property src_info {type:XDC file:3 line:410 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY16 [ get_ports "c0_ddr4_dq[21]" ]
set_property src_info {type:XDC file:3 line:411 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY11 [ get_ports "c0_ddr4_dq[22]" ]
set_property src_info {type:XDC file:3 line:412 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY12 [ get_ports "c0_ddr4_dq[23]" ]
set_property src_info {type:XDC file:3 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BC13 [ get_ports "c0_ddr4_dq[24]" ]
set_property src_info {type:XDC file:3 line:414 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BC14 [ get_ports "c0_ddr4_dq[25]" ]
set_property src_info {type:XDC file:3 line:415 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD14 [ get_ports "c0_ddr4_dq[26]" ]
set_property src_info {type:XDC file:3 line:416 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD15 [ get_ports "c0_ddr4_dq[27]" ]
set_property src_info {type:XDC file:3 line:417 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE16 [ get_ports "c0_ddr4_dq[28]" ]
set_property src_info {type:XDC file:3 line:418 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD16 [ get_ports "c0_ddr4_dq[29]" ]
set_property src_info {type:XDC file:3 line:419 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL15 [ get_ports "c0_ddr4_dq[3]" ]
set_property src_info {type:XDC file:3 line:420 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BF15 [ get_ports "c0_ddr4_dq[30]" ]
set_property src_info {type:XDC file:3 line:421 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE15 [ get_ports "c0_ddr4_dq[31]" ]
set_property src_info {type:XDC file:3 line:422 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL28 [ get_ports "c0_ddr4_dq[32]" ]
set_property src_info {type:XDC file:3 line:423 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL27 [ get_ports "c0_ddr4_dq[33]" ]
set_property src_info {type:XDC file:3 line:424 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN27 [ get_ports "c0_ddr4_dq[34]" ]
set_property src_info {type:XDC file:3 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM27 [ get_ports "c0_ddr4_dq[35]" ]
set_property src_info {type:XDC file:3 line:426 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM25 [ get_ports "c0_ddr4_dq[36]" ]
set_property src_info {type:XDC file:3 line:427 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL25 [ get_ports "c0_ddr4_dq[37]" ]
set_property src_info {type:XDC file:3 line:428 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP28 [ get_ports "c0_ddr4_dq[38]" ]
set_property src_info {type:XDC file:3 line:429 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN28 [ get_ports "c0_ddr4_dq[39]" ]
set_property src_info {type:XDC file:3 line:430 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN13 [ get_ports "c0_ddr4_dq[4]" ]
set_property src_info {type:XDC file:3 line:431 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT28 [ get_ports "c0_ddr4_dq[40]" ]
set_property src_info {type:XDC file:3 line:432 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR28 [ get_ports "c0_ddr4_dq[41]" ]
set_property src_info {type:XDC file:3 line:433 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT27 [ get_ports "c0_ddr4_dq[42]" ]
set_property src_info {type:XDC file:3 line:434 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR27 [ get_ports "c0_ddr4_dq[43]" ]
set_property src_info {type:XDC file:3 line:435 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU27 [ get_ports "c0_ddr4_dq[44]" ]
set_property src_info {type:XDC file:3 line:436 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU26 [ get_ports "c0_ddr4_dq[45]" ]
set_property src_info {type:XDC file:3 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV28 [ get_ports "c0_ddr4_dq[46]" ]
set_property src_info {type:XDC file:3 line:438 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV27 [ get_ports "c0_ddr4_dq[47]" ]
set_property src_info {type:XDC file:3 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY28 [ get_ports "c0_ddr4_dq[48]" ]
set_property src_info {type:XDC file:3 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW28 [ get_ports "c0_ddr4_dq[49]" ]
set_property src_info {type:XDC file:3 line:441 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN14 [ get_ports "c0_ddr4_dq[5]" ]
set_property src_info {type:XDC file:3 line:442 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY27 [ get_ports "c0_ddr4_dq[50]" ]
set_property src_info {type:XDC file:3 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY26 [ get_ports "c0_ddr4_dq[51]" ]
set_property src_info {type:XDC file:3 line:444 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA28 [ get_ports "c0_ddr4_dq[52]" ]
set_property src_info {type:XDC file:3 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA27 [ get_ports "c0_ddr4_dq[53]" ]
set_property src_info {type:XDC file:3 line:446 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB27 [ get_ports "c0_ddr4_dq[54]" ]
set_property src_info {type:XDC file:3 line:447 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB26 [ get_ports "c0_ddr4_dq[55]" ]
set_property src_info {type:XDC file:3 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BC27 [ get_ports "c0_ddr4_dq[56]" ]
set_property src_info {type:XDC file:3 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BC26 [ get_ports "c0_ddr4_dq[57]" ]
set_property src_info {type:XDC file:3 line:450 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BF25 [ get_ports "c0_ddr4_dq[58]" ]
set_property src_info {type:XDC file:3 line:451 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE25 [ get_ports "c0_ddr4_dq[59]" ]
set_property src_info {type:XDC file:3 line:452 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP14 [ get_ports "c0_ddr4_dq[6]" ]
set_property src_info {type:XDC file:3 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE28 [ get_ports "c0_ddr4_dq[60]" ]
set_property src_info {type:XDC file:3 line:454 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD28 [ get_ports "c0_ddr4_dq[61]" ]
set_property src_info {type:XDC file:3 line:455 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BF27 [ get_ports "c0_ddr4_dq[62]" ]
set_property src_info {type:XDC file:3 line:456 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE27 [ get_ports "c0_ddr4_dq[63]" ]
set_property src_info {type:XDC file:3 line:463 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP15 [ get_ports "c0_ddr4_dq[7]" ]
set_property src_info {type:XDC file:3 line:466 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV16 [ get_ports "c0_ddr4_dq[8]" ]
set_property src_info {type:XDC file:3 line:467 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU16 [ get_ports "c0_ddr4_dq[9]" ]
set_property src_info {type:XDC file:3 line:468 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR13 [ get_ports "c0_ddr4_dqs_c[0]" ]
set_property src_info {type:XDC file:3 line:469 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV14 [ get_ports "c0_ddr4_dqs_c[1]" ]
set_property src_info {type:XDC file:3 line:470 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB14 [ get_ports "c0_ddr4_dqs_c[2]" ]
set_property src_info {type:XDC file:3 line:471 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE13 [ get_ports "c0_ddr4_dqs_c[3]" ]
set_property src_info {type:XDC file:3 line:472 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN26 [ get_ports "c0_ddr4_dqs_c[4]" ]
set_property src_info {type:XDC file:3 line:473 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT25 [ get_ports "c0_ddr4_dqs_c[5]" ]
set_property src_info {type:XDC file:3 line:474 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY25 [ get_ports "c0_ddr4_dqs_c[6]" ]
set_property src_info {type:XDC file:3 line:475 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE26 [ get_ports "c0_ddr4_dqs_c[7]" ]
set_property src_info {type:XDC file:3 line:477 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP13 [ get_ports "c0_ddr4_dqs_t[0]" ]
set_property src_info {type:XDC file:3 line:478 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU14 [ get_ports "c0_ddr4_dqs_t[1]" ]
set_property src_info {type:XDC file:3 line:479 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB15 [ get_ports "c0_ddr4_dqs_t[2]" ]
set_property src_info {type:XDC file:3 line:480 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD13 [ get_ports "c0_ddr4_dqs_t[3]" ]
set_property src_info {type:XDC file:3 line:481 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM26 [ get_ports "c0_ddr4_dqs_t[4]" ]
set_property src_info {type:XDC file:3 line:482 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR25 [ get_ports "c0_ddr4_dqs_t[5]" ]
set_property src_info {type:XDC file:3 line:483 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW25 [ get_ports "c0_ddr4_dqs_t[6]" ]
set_property src_info {type:XDC file:3 line:484 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD26 [ get_ports "c0_ddr4_dqs_t[7]" ]
set_property src_info {type:XDC file:3 line:486 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW21 [ get_ports "c0_ddr4_odt[0]" ]
set_property src_info {type:XDC file:3 line:490 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA17 [ get_ports "c0_ddr4_reset_n" ]
set_property src_info {type:XDC file:3 line:495 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AP1 [ get_ports "pci_exp_rxn[0]"]
set_property src_info {type:XDC file:3 line:496 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AR3 [ get_ports "pci_exp_rxn[1]"]
set_property src_info {type:XDC file:3 line:497 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AT1 [ get_ports "pci_exp_rxn[2]"]
set_property src_info {type:XDC file:3 line:498 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AU3 [ get_ports "pci_exp_rxn[3]"]
set_property src_info {type:XDC file:3 line:499 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AV1 [ get_ports "pci_exp_rxn[4]"]
set_property src_info {type:XDC file:3 line:500 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AW3 [ get_ports "pci_exp_rxn[5]"]
set_property src_info {type:XDC file:3 line:501 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 BA1 [ get_ports "pci_exp_rxn[6]"]
set_property src_info {type:XDC file:3 line:502 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 BC1 [ get_ports "pci_exp_rxn[7]"]
set_property src_info {type:XDC file:3 line:503 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AP2 [ get_ports "pci_exp_rxp[0]"]
set_property src_info {type:XDC file:3 line:504 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AR4 [ get_ports "pci_exp_rxp[1]"]
set_property src_info {type:XDC file:3 line:505 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AT2 [ get_ports "pci_exp_rxp[2]"]
set_property src_info {type:XDC file:3 line:506 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AU4 [ get_ports "pci_exp_rxp[3]"]
set_property src_info {type:XDC file:3 line:507 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AV2 [ get_ports "pci_exp_rxp[4]"]
set_property src_info {type:XDC file:3 line:508 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AW4 [ get_ports "pci_exp_rxp[5]"]
set_property src_info {type:XDC file:3 line:509 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 BA2 [ get_ports "pci_exp_rxp[6]"]
set_property src_info {type:XDC file:3 line:510 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 BC2 [ get_ports "pci_exp_rxp[7]"]
set_property src_info {type:XDC file:3 line:511 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AP6 [ get_ports "pci_exp_txn[0]"]
set_property src_info {type:XDC file:3 line:512 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AR8 [ get_ports "pci_exp_txn[1]"]
set_property src_info {type:XDC file:3 line:513 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AT6 [ get_ports "pci_exp_txn[2]"]
set_property src_info {type:XDC file:3 line:514 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AU8 [ get_ports "pci_exp_txn[3]"]
set_property src_info {type:XDC file:3 line:515 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AV6 [ get_ports "pci_exp_txn[4]"]
set_property src_info {type:XDC file:3 line:516 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 BB4 [ get_ports "pci_exp_txn[5]"]
set_property src_info {type:XDC file:3 line:517 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 BD4 [ get_ports "pci_exp_txn[6]"]
set_property src_info {type:XDC file:3 line:518 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 BF4 [ get_ports "pci_exp_txn[7]"]
set_property src_info {type:XDC file:3 line:519 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AP7 [ get_ports "pci_exp_txp[0]"]
set_property src_info {type:XDC file:3 line:520 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AR9 [ get_ports "pci_exp_txp[1]"]
set_property src_info {type:XDC file:3 line:521 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AT7 [ get_ports "pci_exp_txp[2]"]
set_property src_info {type:XDC file:3 line:522 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AU9 [ get_ports "pci_exp_txp[3]"]
set_property src_info {type:XDC file:3 line:523 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AV7 [ get_ports "pci_exp_txp[4]"]
set_property src_info {type:XDC file:3 line:524 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 BB5 [ get_ports "pci_exp_txp[5]"]
set_property src_info {type:XDC file:3 line:525 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 BD5 [ get_ports "pci_exp_txp[6]"]
set_property src_info {type:XDC file:3 line:526 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 BF5 [ get_ports "pci_exp_txp[7]"]
