set_property SRC_FILE_INFO {cfile:C:/Users/yongj/Desktop/softmc_ddr4/hw/boards/ML605/project_1/project_1.srcs/constrs_1/imports/xusps3_config/xusps3_pinout.xdc rfile:../../../project_1.srcs/constrs_1/imports/xusps3_config/xusps3_pinout.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR26 [get_ports sys_reset_n]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV18 [get_ports "c0_sys_clk_p"]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW18 [get_ports "c0_sys_clk_n"]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT23 [get_ports "sys_rst_l"]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT11 [get_ports "sys_clk_p"]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT10 [get_ports "sys_clk_n"]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV22 [get_ports "c0_init_calib_complete"]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR22 [get_ports {leds[0]}]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT22 [get_ports {leds[1]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR23 [get_ports {leds[2]}]
set_property src_info {type:XDC file:1 line:370 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT18 [ get_ports "c0_ddr4_adr[0]" ]
set_property src_info {type:XDC file:1 line:371 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU17 [ get_ports "c0_ddr4_adr[1]" ]
set_property src_info {type:XDC file:1 line:372 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP19 [ get_ports "c0_ddr4_adr[10]" ]
set_property src_info {type:XDC file:1 line:373 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM16 [ get_ports "c0_ddr4_adr[11]" ]
set_property src_info {type:XDC file:1 line:374 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN16 [ get_ports "c0_ddr4_adr[12]" ]
set_property src_info {type:XDC file:1 line:375 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL19 [ get_ports "c0_ddr4_adr[13]" ]
set_property src_info {type:XDC file:1 line:376 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM19 [ get_ports "c0_ddr4_adr[14]" ]
set_property src_info {type:XDC file:1 line:377 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL20 [ get_ports "c0_ddr4_adr[15]" ]
set_property src_info {type:XDC file:1 line:378 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM20 [ get_ports "c0_ddr4_adr[16]" ]
set_property src_info {type:XDC file:1 line:379 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP18 [ get_ports "c0_ddr4_adr[2]" ]
set_property src_info {type:XDC file:1 line:380 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR18 [ get_ports "c0_ddr4_adr[3]" ]
set_property src_info {type:XDC file:1 line:381 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP20 [ get_ports "c0_ddr4_adr[4]" ]
set_property src_info {type:XDC file:1 line:382 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR20 [ get_ports "c0_ddr4_adr[5]" ]
set_property src_info {type:XDC file:1 line:383 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU21 [ get_ports "c0_ddr4_adr[6]" ]
set_property src_info {type:XDC file:1 line:384 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN18 [ get_ports "c0_ddr4_adr[7]" ]
set_property src_info {type:XDC file:1 line:385 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN17 [ get_ports "c0_ddr4_adr[8]" ]
set_property src_info {type:XDC file:1 line:386 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN19 [ get_ports "c0_ddr4_adr[9]" ]
set_property src_info {type:XDC file:1 line:387 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV17 [ get_ports "c0_ddr4_act_n" ]
set_property src_info {type:XDC file:1 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT19 [ get_ports "c0_ddr4_ba[0]" ]
set_property src_info {type:XDC file:1 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU19 [ get_ports "c0_ddr4_ba[1]" ]
set_property src_info {type:XDC file:1 line:390 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT20 [ get_ports "c0_ddr4_bg[0]" ]
set_property src_info {type:XDC file:1 line:392 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT17 [ get_ports "c0_ddr4_ck_c[0]" ]
set_property src_info {type:XDC file:1 line:393 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR17 [ get_ports "c0_ddr4_ck_t[0]" ]
set_property src_info {type:XDC file:1 line:396 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY20 [ get_ports "c0_ddr4_cke[0]" ]
set_property src_info {type:XDC file:1 line:398 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA18 [ get_ports "c0_ddr4_cs_n[0]" ]
set_property src_info {type:XDC file:1 line:400 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR16 [ get_ports "c0_ddr4_dm_dbi_n[0]" ]
set_property src_info {type:XDC file:1 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW14 [ get_ports "c0_ddr4_dm_dbi_n[1]" ]
set_property src_info {type:XDC file:1 line:402 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA12 [ get_ports "c0_ddr4_dm_dbi_n[2]" ]
set_property src_info {type:XDC file:1 line:403 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BF14 [ get_ports "c0_ddr4_dm_dbi_n[3]" ]
set_property src_info {type:XDC file:1 line:404 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP25 [ get_ports "c0_ddr4_dm_dbi_n[4]" ]
set_property src_info {type:XDC file:1 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV26 [ get_ports "c0_ddr4_dm_dbi_n[5]" ]
set_property src_info {type:XDC file:1 line:406 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA25 [ get_ports "c0_ddr4_dm_dbi_n[6]" ]
set_property src_info {type:XDC file:1 line:407 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BF28 [ get_ports "c0_ddr4_dm_dbi_n[7]" ]
set_property src_info {type:XDC file:1 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM14 [ get_ports "c0_ddr4_dq[0]" ]
set_property src_info {type:XDC file:1 line:410 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL14 [ get_ports "c0_ddr4_dq[1]" ]
set_property src_info {type:XDC file:1 line:411 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU15 [ get_ports "c0_ddr4_dq[10]" ]
set_property src_info {type:XDC file:1 line:412 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT15 [ get_ports "c0_ddr4_dq[11]" ]
set_property src_info {type:XDC file:1 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV13 [ get_ports "c0_ddr4_dq[12]" ]
set_property src_info {type:XDC file:1 line:414 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU13 [ get_ports "c0_ddr4_dq[13]" ]
set_property src_info {type:XDC file:1 line:415 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW15 [ get_ports "c0_ddr4_dq[14]" ]
set_property src_info {type:XDC file:1 line:416 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW16 [ get_ports "c0_ddr4_dq[15]" ]
set_property src_info {type:XDC file:1 line:417 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA13 [ get_ports "c0_ddr4_dq[16]" ]
set_property src_info {type:XDC file:1 line:418 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY13 [ get_ports "c0_ddr4_dq[17]" ]
set_property src_info {type:XDC file:1 line:419 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA14 [ get_ports "c0_ddr4_dq[18]" ]
set_property src_info {type:XDC file:1 line:420 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA15 [ get_ports "c0_ddr4_dq[19]" ]
set_property src_info {type:XDC file:1 line:421 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM15 [ get_ports "c0_ddr4_dq[2]" ]
set_property src_info {type:XDC file:1 line:422 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY15 [ get_ports "c0_ddr4_dq[20]" ]
set_property src_info {type:XDC file:1 line:423 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY16 [ get_ports "c0_ddr4_dq[21]" ]
set_property src_info {type:XDC file:1 line:424 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY11 [ get_ports "c0_ddr4_dq[22]" ]
set_property src_info {type:XDC file:1 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY12 [ get_ports "c0_ddr4_dq[23]" ]
set_property src_info {type:XDC file:1 line:426 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BC13 [ get_ports "c0_ddr4_dq[24]" ]
set_property src_info {type:XDC file:1 line:427 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BC14 [ get_ports "c0_ddr4_dq[25]" ]
set_property src_info {type:XDC file:1 line:428 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD14 [ get_ports "c0_ddr4_dq[26]" ]
set_property src_info {type:XDC file:1 line:429 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD15 [ get_ports "c0_ddr4_dq[27]" ]
set_property src_info {type:XDC file:1 line:430 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE16 [ get_ports "c0_ddr4_dq[28]" ]
set_property src_info {type:XDC file:1 line:431 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD16 [ get_ports "c0_ddr4_dq[29]" ]
set_property src_info {type:XDC file:1 line:432 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL15 [ get_ports "c0_ddr4_dq[3]" ]
set_property src_info {type:XDC file:1 line:433 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BF15 [ get_ports "c0_ddr4_dq[30]" ]
set_property src_info {type:XDC file:1 line:434 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE15 [ get_ports "c0_ddr4_dq[31]" ]
set_property src_info {type:XDC file:1 line:435 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL28 [ get_ports "c0_ddr4_dq[32]" ]
set_property src_info {type:XDC file:1 line:436 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL27 [ get_ports "c0_ddr4_dq[33]" ]
set_property src_info {type:XDC file:1 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN27 [ get_ports "c0_ddr4_dq[34]" ]
set_property src_info {type:XDC file:1 line:438 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM27 [ get_ports "c0_ddr4_dq[35]" ]
set_property src_info {type:XDC file:1 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM25 [ get_ports "c0_ddr4_dq[36]" ]
set_property src_info {type:XDC file:1 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL25 [ get_ports "c0_ddr4_dq[37]" ]
set_property src_info {type:XDC file:1 line:441 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP28 [ get_ports "c0_ddr4_dq[38]" ]
set_property src_info {type:XDC file:1 line:442 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN28 [ get_ports "c0_ddr4_dq[39]" ]
set_property src_info {type:XDC file:1 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN13 [ get_ports "c0_ddr4_dq[4]" ]
set_property src_info {type:XDC file:1 line:444 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT28 [ get_ports "c0_ddr4_dq[40]" ]
set_property src_info {type:XDC file:1 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR28 [ get_ports "c0_ddr4_dq[41]" ]
set_property src_info {type:XDC file:1 line:446 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT27 [ get_ports "c0_ddr4_dq[42]" ]
set_property src_info {type:XDC file:1 line:447 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR27 [ get_ports "c0_ddr4_dq[43]" ]
set_property src_info {type:XDC file:1 line:448 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU27 [ get_ports "c0_ddr4_dq[44]" ]
set_property src_info {type:XDC file:1 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU26 [ get_ports "c0_ddr4_dq[45]" ]
set_property src_info {type:XDC file:1 line:450 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV28 [ get_ports "c0_ddr4_dq[46]" ]
set_property src_info {type:XDC file:1 line:451 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV27 [ get_ports "c0_ddr4_dq[47]" ]
set_property src_info {type:XDC file:1 line:452 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY28 [ get_ports "c0_ddr4_dq[48]" ]
set_property src_info {type:XDC file:1 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW28 [ get_ports "c0_ddr4_dq[49]" ]
set_property src_info {type:XDC file:1 line:454 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN14 [ get_ports "c0_ddr4_dq[5]" ]
set_property src_info {type:XDC file:1 line:455 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY27 [ get_ports "c0_ddr4_dq[50]" ]
set_property src_info {type:XDC file:1 line:456 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY26 [ get_ports "c0_ddr4_dq[51]" ]
set_property src_info {type:XDC file:1 line:457 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA28 [ get_ports "c0_ddr4_dq[52]" ]
set_property src_info {type:XDC file:1 line:458 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA27 [ get_ports "c0_ddr4_dq[53]" ]
set_property src_info {type:XDC file:1 line:459 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB27 [ get_ports "c0_ddr4_dq[54]" ]
set_property src_info {type:XDC file:1 line:460 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB26 [ get_ports "c0_ddr4_dq[55]" ]
set_property src_info {type:XDC file:1 line:461 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BC27 [ get_ports "c0_ddr4_dq[56]" ]
set_property src_info {type:XDC file:1 line:462 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BC26 [ get_ports "c0_ddr4_dq[57]" ]
set_property src_info {type:XDC file:1 line:463 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BF25 [ get_ports "c0_ddr4_dq[58]" ]
set_property src_info {type:XDC file:1 line:464 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE25 [ get_ports "c0_ddr4_dq[59]" ]
set_property src_info {type:XDC file:1 line:465 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP14 [ get_ports "c0_ddr4_dq[6]" ]
set_property src_info {type:XDC file:1 line:466 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE28 [ get_ports "c0_ddr4_dq[60]" ]
set_property src_info {type:XDC file:1 line:467 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD28 [ get_ports "c0_ddr4_dq[61]" ]
set_property src_info {type:XDC file:1 line:468 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BF27 [ get_ports "c0_ddr4_dq[62]" ]
set_property src_info {type:XDC file:1 line:469 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE27 [ get_ports "c0_ddr4_dq[63]" ]
set_property src_info {type:XDC file:1 line:476 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP15 [ get_ports "c0_ddr4_dq[7]" ]
set_property src_info {type:XDC file:1 line:479 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV16 [ get_ports "c0_ddr4_dq[8]" ]
set_property src_info {type:XDC file:1 line:480 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU16 [ get_ports "c0_ddr4_dq[9]" ]
set_property src_info {type:XDC file:1 line:481 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR13 [ get_ports "c0_ddr4_dqs_c[0]" ]
set_property src_info {type:XDC file:1 line:482 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV14 [ get_ports "c0_ddr4_dqs_c[1]" ]
set_property src_info {type:XDC file:1 line:483 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB14 [ get_ports "c0_ddr4_dqs_c[2]" ]
set_property src_info {type:XDC file:1 line:484 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE13 [ get_ports "c0_ddr4_dqs_c[3]" ]
set_property src_info {type:XDC file:1 line:485 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN26 [ get_ports "c0_ddr4_dqs_c[4]" ]
set_property src_info {type:XDC file:1 line:486 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT25 [ get_ports "c0_ddr4_dqs_c[5]" ]
set_property src_info {type:XDC file:1 line:487 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AY25 [ get_ports "c0_ddr4_dqs_c[6]" ]
set_property src_info {type:XDC file:1 line:488 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BE26 [ get_ports "c0_ddr4_dqs_c[7]" ]
set_property src_info {type:XDC file:1 line:490 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP13 [ get_ports "c0_ddr4_dqs_t[0]" ]
set_property src_info {type:XDC file:1 line:491 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU14 [ get_ports "c0_ddr4_dqs_t[1]" ]
set_property src_info {type:XDC file:1 line:492 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BB15 [ get_ports "c0_ddr4_dqs_t[2]" ]
set_property src_info {type:XDC file:1 line:493 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD13 [ get_ports "c0_ddr4_dqs_t[3]" ]
set_property src_info {type:XDC file:1 line:494 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM26 [ get_ports "c0_ddr4_dqs_t[4]" ]
set_property src_info {type:XDC file:1 line:495 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR25 [ get_ports "c0_ddr4_dqs_t[5]" ]
set_property src_info {type:XDC file:1 line:496 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW25 [ get_ports "c0_ddr4_dqs_t[6]" ]
set_property src_info {type:XDC file:1 line:497 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BD26 [ get_ports "c0_ddr4_dqs_t[7]" ]
set_property src_info {type:XDC file:1 line:499 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AW21 [ get_ports "c0_ddr4_odt[0]" ]
set_property src_info {type:XDC file:1 line:503 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN BA17 [ get_ports "c0_ddr4_reset_n" ]
set_property src_info {type:XDC file:1 line:508 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AP1 [ get_ports "pci_exp_rxn[0]"]
set_property src_info {type:XDC file:1 line:509 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AR3 [ get_ports "pci_exp_rxn[1]"]
set_property src_info {type:XDC file:1 line:510 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AT1 [ get_ports "pci_exp_rxn[2]"]
set_property src_info {type:XDC file:1 line:511 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AU3 [ get_ports "pci_exp_rxn[3]"]
set_property src_info {type:XDC file:1 line:512 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AV1 [ get_ports "pci_exp_rxn[4]"]
set_property src_info {type:XDC file:1 line:513 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AW3 [ get_ports "pci_exp_rxn[5]"]
set_property src_info {type:XDC file:1 line:514 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 BA1 [ get_ports "pci_exp_rxn[6]"]
set_property src_info {type:XDC file:1 line:515 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 BC1 [ get_ports "pci_exp_rxn[7]"]
set_property src_info {type:XDC file:1 line:516 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AP2 [ get_ports "pci_exp_rxp[0]"]
set_property src_info {type:XDC file:1 line:517 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AR4 [ get_ports "pci_exp_rxp[1]"]
set_property src_info {type:XDC file:1 line:518 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AT2 [ get_ports "pci_exp_rxp[2]"]
set_property src_info {type:XDC file:1 line:519 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AU4 [ get_ports "pci_exp_rxp[3]"]
set_property src_info {type:XDC file:1 line:520 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AV2 [ get_ports "pci_exp_rxp[4]"]
set_property src_info {type:XDC file:1 line:521 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AW4 [ get_ports "pci_exp_rxp[5]"]
set_property src_info {type:XDC file:1 line:522 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 BA2 [ get_ports "pci_exp_rxp[6]"]
set_property src_info {type:XDC file:1 line:523 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 BC2 [ get_ports "pci_exp_rxp[7]"]
set_property src_info {type:XDC file:1 line:524 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AP6 [ get_ports "pci_exp_txn[0]"]
set_property src_info {type:XDC file:1 line:525 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AR8 [ get_ports "pci_exp_txn[1]"]
set_property src_info {type:XDC file:1 line:526 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AT6 [ get_ports "pci_exp_txn[2]"]
set_property src_info {type:XDC file:1 line:527 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AU8 [ get_ports "pci_exp_txn[3]"]
set_property src_info {type:XDC file:1 line:528 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AV6 [ get_ports "pci_exp_txn[4]"]
set_property src_info {type:XDC file:1 line:529 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 BB4 [ get_ports "pci_exp_txn[5]"]
set_property src_info {type:XDC file:1 line:530 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 BD4 [ get_ports "pci_exp_txn[6]"]
set_property src_info {type:XDC file:1 line:531 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 BF4 [ get_ports "pci_exp_txn[7]"]
set_property src_info {type:XDC file:1 line:532 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AP7 [ get_ports "pci_exp_txp[0]"]
set_property src_info {type:XDC file:1 line:533 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AR9 [ get_ports "pci_exp_txp[1]"]
set_property src_info {type:XDC file:1 line:534 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AT7 [ get_ports "pci_exp_txp[2]"]
set_property src_info {type:XDC file:1 line:535 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AU9 [ get_ports "pci_exp_txp[3]"]
set_property src_info {type:XDC file:1 line:536 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 AV7 [ get_ports "pci_exp_txp[4]"]
set_property src_info {type:XDC file:1 line:537 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 BB5 [ get_ports "pci_exp_txp[5]"]
set_property src_info {type:XDC file:1 line:538 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 BD5 [ get_ports "pci_exp_txp[6]"]
set_property src_info {type:XDC file:1 line:539 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN	 BF5 [ get_ports "pci_exp_txp[7]"]
